version: '3'
services:
  local-db:
    image: library/mysql:5.7
    container_name: dev-to-do-note
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dev-to-do-note
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64
