version: '3'

services:
  db-local-mysql:
    image: library/mysql:5.7
    container_name: dev-to-do-note
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    platform: linux/x86_64
